// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence.Models;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(FluencyLocalDbContext))]
    partial class FluencyLocalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Persistence.Models.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("actividad_pkey");

                    b.ToTable("actividad", (string)null);
                });

            modelBuilder.Entity("Persistence.Models.ActividadOportunidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateTime?>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_hora")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("IdContacto")
                        .HasColumnType("integer")
                        .HasColumnName("id_contacto");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<int?>("IdOportunidad")
                        .HasColumnType("integer")
                        .HasColumnName("id_oportunidad");

                    b.Property<int?>("IdTipoActividad")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_actividad");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Resultado")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("resultado");

                    b.HasKey("Id")
                        .HasName("actividad_oportunidad_pkey");

                    b.HasIndex("IdContacto");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdOportunidad");

                    b.HasIndex("IdTipoActividad");

                    b.HasIndex("IdUsuario");

                    b.ToTable("actividad_oportunidad", (string)null);
                });

            modelBuilder.Entity("Persistence.Models.Contacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Cargo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cargo");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Documento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("documento");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("integer")
                        .HasColumnName("id_estado");

                    b.Property<int?>("IdOrigen")
                        .HasColumnType("integer")
                        .HasColumnName("id_origen");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("contacto_pkey");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdOrigen");

                    b.ToTable("contacto", (string)null);
                });

            modelBuilder.Entity("Persistence.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Cuit")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cuit");

                    b.Property<string>("Direccion")
                        .HasColumnType("text")
                        .HasColumnName("direccion");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("integer")
                        .HasColumnName("id_estado");

                    b.Property<int?>("IdOrigen")
                        .HasColumnType("integer")
                        .HasColumnName("id_origen");

                    b.Property<string>("Industria")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("industria");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("razon_social");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("telefono");

                    b.HasKey("Id")
                        .HasName("empresa_pkey");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdOrigen");

                    b.ToTable("empresa", (string)null);
                });

            modelBuilder.Entity("Persistence.Models.EstadoCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("estado_cliente_pkey");

                    b.ToTable("estado_cliente", (string)null);
                });

            modelBuilder.Entity("Persistence.Models.EstadoOportunidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("estado_oportunidad_pkey");

                    b.ToTable("estado_oportunidad", (string)null);
                });

            modelBuilder.Entity("Persistence.Models.EtapaComercial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.HasKey("Id")
                        .HasName("etapa_comercial_pkey");

                    b.ToTable("etapa_comercial", (string)null);
                });

            modelBuilder.Entity("Persistence.Models.HistorialEtapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("IdEtapaAnterior")
                        .HasColumnType("integer")
                        .HasColumnName("id_etapa_anterior");

                    b.Property<int?>("IdNuevaEtapa")
                        .HasColumnType("integer")
                        .HasColumnName("id_nueva_etapa");

                    b.Property<int?>("IdOportunidad")
                        .HasColumnType("integer")
                        .HasColumnName("id_oportunidad");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Observacion")
                        .HasColumnType("text")
                        .HasColumnName("observacion");

                    b.HasKey("Id")
                        .HasName("historial_etapas_pkey");

                    b.HasIndex("IdEtapaAnterior");

                    b.HasIndex("IdNuevaEtapa");

                    b.HasIndex("IdOportunidad");

                    b.HasIndex("IdUsuario");

                    b.ToTable("historial_etapas", (string)null);
                });

            modelBuilder.Entity("Persistence.Models.LogOportunidadCambio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Campo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("campo");

                    b.Property<DateTime?>("FechaHora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_hora")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("IdOportunidad")
                        .HasColumnType("integer")
                        .HasColumnName("id_oportunidad");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("ValorAnterior")
                        .HasColumnType("text")
                        .HasColumnName("valor_anterior");

                    b.Property<string>("ValorNuevo")
                        .HasColumnType("text")
                        .HasColumnName("valor_nuevo");

                    b.HasKey("Id")
                        .HasName("log_oportunidad_cambio_pkey");

                    b.HasIndex("IdOportunidad");

                    b.HasIndex("IdUsuario");

                    b.ToTable("log_oportunidad_cambio", (string)null);
                });

            modelBuilder.Entity("Persistence.Models.Modalidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("modalidad_pkey");

                    b.ToTable("modalidad", (string)null);
                });

            modelBuilder.Entity("Persistence.Models.MotivoRechazo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("motivo_rechazo_pkey");

                    b.ToTable("motivo_rechazo", (string)null);
                });

            modelBuilder.Entity("Persistence.Models.NivelIngles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("nivel_ingles_pkey");

                    b.ToTable("nivel_ingles", (string)null);
                });

            modelBuilder.Entity("Persistence.Models.Oportunidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("fecha_cierre");

                    b.Property<DateOnly?>("FechaEstimadaCierre")
                        .HasColumnType("date")
                        .HasColumnName("fecha_estimada_cierre");

                    b.Property<int?>("IdContacto")
                        .HasColumnType("integer")
                        .HasColumnName("id_contacto");

                    b.Property<int?>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<int?>("IdEstado")
                        .HasColumnType("integer")
                        .HasColumnName("id_estado");

                    b.Property<int?>("IdEtapa")
                        .HasColumnType("integer")
                        .HasColumnName("id_etapa");

                    b.Property<int?>("IdOrigen")
                        .HasColumnType("integer")
                        .HasColumnName("id_origen");

                    b.Property<int?>("IdServicio")
                        .HasColumnType("integer")
                        .HasColumnName("id_servicio");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("oportunidad_pkey");

                    b.HasIndex("IdContacto");

                    b.HasIndex("IdEmpresa");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdEtapa");

                    b.HasIndex("IdOrigen");

                    b.HasIndex("IdServicio");

                    b.HasIndex("IdUsuario");

                    b.ToTable("oportunidad", (string)null);
                });

            modelBuilder.Entity("Persistence.Models.OportunidadItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("cantidad");

                    b.Property<decimal?>("Descuento")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("descuento");

                    b.Property<int?>("IdOportunidad")
                        .HasColumnType("integer")
                        .HasColumnName("id_oportunidad");

                    b.Property<int?>("IdServicio")
                        .HasColumnType("integer")
                        .HasColumnName("id_servicio");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_unitario");

                    b.HasKey("Id")
                        .HasName("oportunidad_item_pkey");

                    b.HasIndex("IdOportunidad");

                    b.HasIndex("IdServicio");

                    b.ToTable("oportunidad_item", (string)null);
                });

            modelBuilder.Entity("Persistence.Models.OrigenComercial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("origen_comercial_pkey");

                    b.ToTable("origen_comercial", (string)null);
                });

            modelBuilder.Entity("Persistence.Models.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.HasKey("Id")
                        .HasName("permiso_pkey");

                    b.ToTable("permiso", (string)null);
                });

            modelBuilder.Entity("Persistence.Models.PermisoRol", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("integer")
                        .HasColumnName("id_permiso");

                    b.HasKey("IdRol", "IdPermiso")
                        .HasName("permiso_rol_pkey");

                    b.HasIndex("IdPermiso");

                    b.ToTable("permiso_rol", (string)null);
                });

            modelBuilder.Entity("Persistence.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre");

                    b.HasKey("Id")
                        .HasName("rol_pkey");

                    b.HasIndex(new[] { "Nombre" }, "rol_nombre_key")
                        .IsUnique();

                    b.ToTable("rol", (string)null);
                });

            modelBuilder.Entity("Persistence.Models.Servicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int?>("DuracionHoras")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_horas");

                    b.Property<int?>("IdModalidad")
                        .HasColumnType("integer")
                        .HasColumnName("id_modalidad");

                    b.Property<int?>("IdNivel")
                        .HasColumnType("integer")
                        .HasColumnName("id_nivel");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioReferencia")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("precio_referencia");

                    b.HasKey("Id")
                        .HasName("servicio_pkey");

                    b.HasIndex("IdModalidad");

                    b.HasIndex("IdNivel");

                    b.ToTable("servicio", (string)null);
                });

            modelBuilder.Entity("Persistence.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("activo");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellido");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("correo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("usuario_pkey");

                    b.HasIndex(new[] { "Correo" }, "usuario_correo_key")
                        .IsUnique();

                    b.HasIndex(new[] { "Username" }, "usuario_username_key")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Persistence.Models.UsuarioRol", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.HasKey("IdUsuario", "IdRol")
                        .HasName("usuario_rol_pkey");

                    b.HasIndex("IdRol");

                    b.ToTable("usuario_rol", (string)null);
                });

            modelBuilder.Entity("Persistence.Models.ActividadOportunidad", b =>
                {
                    b.HasOne("Persistence.Models.Contacto", "IdContactoNavigation")
                        .WithMany("ActividadOportunidades")
                        .HasForeignKey("IdContacto")
                        .HasConstraintName("actividad_oportunidad_id_contacto_fkey");

                    b.HasOne("Persistence.Models.Empresa", "IdEmpresaNavigation")
                        .WithMany("ActividadOportunidades")
                        .HasForeignKey("IdEmpresa")
                        .HasConstraintName("actividad_oportunidad_id_empresa_fkey");

                    b.HasOne("Persistence.Models.Oportunidad", "IdOportunidadNavigation")
                        .WithMany("ActividadOportunidades")
                        .HasForeignKey("IdOportunidad")
                        .HasConstraintName("actividad_oportunidad_id_oportunidad_fkey");

                    b.HasOne("Persistence.Models.Actividad", "IdTipoActividadNavigation")
                        .WithMany("ActividadOportunidades")
                        .HasForeignKey("IdTipoActividad")
                        .HasConstraintName("actividad_oportunidad_id_tipo_actividad_fkey");

                    b.HasOne("Persistence.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("ActividadOportunidades")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("actividad_oportunidad_id_usuario_fkey");

                    b.Navigation("IdContactoNavigation");

                    b.Navigation("IdEmpresaNavigation");

                    b.Navigation("IdOportunidadNavigation");

                    b.Navigation("IdTipoActividadNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Persistence.Models.Contacto", b =>
                {
                    b.HasOne("Persistence.Models.Empresa", "IdEmpresaNavigation")
                        .WithMany("Contactos")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("contacto_id_empresa_fkey");

                    b.HasOne("Persistence.Models.EstadoCliente", "IdEstadoNavigation")
                        .WithMany("Contactos")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("contacto_id_estado_fkey");

                    b.HasOne("Persistence.Models.OrigenComercial", "IdOrigenNavigation")
                        .WithMany("Contactos")
                        .HasForeignKey("IdOrigen")
                        .HasConstraintName("contacto_id_origen_fkey");

                    b.Navigation("IdEmpresaNavigation");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdOrigenNavigation");
                });

            modelBuilder.Entity("Persistence.Models.Empresa", b =>
                {
                    b.HasOne("Persistence.Models.EstadoCliente", "IdEstadoNavigation")
                        .WithMany("Empresas")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("empresa_id_estado_fkey");

                    b.HasOne("Persistence.Models.OrigenComercial", "IdOrigenNavigation")
                        .WithMany("Empresas")
                        .HasForeignKey("IdOrigen")
                        .HasConstraintName("empresa_id_origen_fkey");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdOrigenNavigation");
                });

            modelBuilder.Entity("Persistence.Models.HistorialEtapa", b =>
                {
                    b.HasOne("Persistence.Models.EtapaComercial", "IdEtapaAnteriorNavigation")
                        .WithMany("HistorialEtapaIdEtapaAnteriorNavigations")
                        .HasForeignKey("IdEtapaAnterior")
                        .HasConstraintName("historial_etapas_id_etapa_anterior_fkey");

                    b.HasOne("Persistence.Models.EtapaComercial", "IdNuevaEtapaNavigation")
                        .WithMany("HistorialEtapaIdNuevaEtapaNavigations")
                        .HasForeignKey("IdNuevaEtapa")
                        .HasConstraintName("historial_etapas_id_nueva_etapa_fkey");

                    b.HasOne("Persistence.Models.Oportunidad", "IdOportunidadNavigation")
                        .WithMany("HistorialEtapas")
                        .HasForeignKey("IdOportunidad")
                        .HasConstraintName("historial_etapas_id_oportunidad_fkey");

                    b.HasOne("Persistence.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("HistorialEtapas")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("historial_etapas_id_usuario_fkey");

                    b.Navigation("IdEtapaAnteriorNavigation");

                    b.Navigation("IdNuevaEtapaNavigation");

                    b.Navigation("IdOportunidadNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Persistence.Models.LogOportunidadCambio", b =>
                {
                    b.HasOne("Persistence.Models.Oportunidad", "IdOportunidadNavigation")
                        .WithMany("LogOportunidadCambios")
                        .HasForeignKey("IdOportunidad")
                        .HasConstraintName("log_oportunidad_cambio_id_oportunidad_fkey");

                    b.HasOne("Persistence.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("LogOportunidadCambios")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("log_oportunidad_cambio_id_usuario_fkey");

                    b.Navigation("IdOportunidadNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Persistence.Models.Oportunidad", b =>
                {
                    b.HasOne("Persistence.Models.Contacto", "IdContactoNavigation")
                        .WithMany("Oportunidades")
                        .HasForeignKey("IdContacto")
                        .HasConstraintName("oportunidad_id_contacto_fkey");

                    b.HasOne("Persistence.Models.Empresa", "IdEmpresaNavigation")
                        .WithMany("Oportunidades")
                        .HasForeignKey("IdEmpresa")
                        .HasConstraintName("oportunidad_id_empresa_fkey");

                    b.HasOne("Persistence.Models.EstadoCliente", "IdEstadoNavigation")
                        .WithMany("Oportunidades")
                        .HasForeignKey("IdEstado")
                        .HasConstraintName("oportunidad_id_estado_fkey");

                    b.HasOne("Persistence.Models.EtapaComercial", "IdEtapaNavigation")
                        .WithMany("Oportunidades")
                        .HasForeignKey("IdEtapa")
                        .HasConstraintName("oportunidad_id_etapa_fkey");

                    b.HasOne("Persistence.Models.OrigenComercial", "IdOrigenNavigation")
                        .WithMany("Oportunidades")
                        .HasForeignKey("IdOrigen")
                        .HasConstraintName("oportunidad_id_origen_fkey");

                    b.HasOne("Persistence.Models.Servicio", "IdServicioNavigation")
                        .WithMany("Oportunidades")
                        .HasForeignKey("IdServicio")
                        .HasConstraintName("oportunidad_id_servicio_fkey");

                    b.HasOne("Persistence.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Oportunidades")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("oportunidad_id_usuario_fkey");

                    b.Navigation("IdContactoNavigation");

                    b.Navigation("IdEmpresaNavigation");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdEtapaNavigation");

                    b.Navigation("IdOrigenNavigation");

                    b.Navigation("IdServicioNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Persistence.Models.OportunidadItem", b =>
                {
                    b.HasOne("Persistence.Models.Oportunidad", "IdOportunidadNavigation")
                        .WithMany("OportunidadItems")
                        .HasForeignKey("IdOportunidad")
                        .HasConstraintName("oportunidad_item_id_oportunidad_fkey");

                    b.HasOne("Persistence.Models.Servicio", "IdServicioNavigation")
                        .WithMany("OportunidadItems")
                        .HasForeignKey("IdServicio")
                        .HasConstraintName("oportunidad_item_id_servicio_fkey");

                    b.Navigation("IdOportunidadNavigation");

                    b.Navigation("IdServicioNavigation");
                });

            modelBuilder.Entity("Persistence.Models.PermisoRol", b =>
                {
                    b.HasOne("Persistence.Models.Permiso", "IdPermisoNavigation")
                        .WithMany("PermisoRoles")
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("permiso_rol_id_permiso_fkey");

                    b.HasOne("Persistence.Models.Rol", "IdRolNavigation")
                        .WithMany("PermisoRoles")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("permiso_rol_id_rol_fkey");

                    b.Navigation("IdPermisoNavigation");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("Persistence.Models.Servicio", b =>
                {
                    b.HasOne("Persistence.Models.Modalidad", "IdModalidadNavigation")
                        .WithMany("Servicios")
                        .HasForeignKey("IdModalidad")
                        .HasConstraintName("servicio_id_modalidad_fkey");

                    b.HasOne("Persistence.Models.NivelIngles", "IdNivelNavigation")
                        .WithMany("Servicios")
                        .HasForeignKey("IdNivel")
                        .HasConstraintName("servicio_id_nivel_fkey");

                    b.Navigation("IdModalidadNavigation");

                    b.Navigation("IdNivelNavigation");
                });

            modelBuilder.Entity("Persistence.Models.UsuarioRol", b =>
                {
                    b.HasOne("Persistence.Models.Rol", "IdRolNavigation")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("usuario_rol_id_rol_fkey");

                    b.HasOne("Persistence.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("usuario_rol_id_usuario_fkey");

                    b.Navigation("IdRolNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Persistence.Models.Actividad", b =>
                {
                    b.Navigation("ActividadOportunidades");
                });

            modelBuilder.Entity("Persistence.Models.Contacto", b =>
                {
                    b.Navigation("ActividadOportunidades");

                    b.Navigation("Oportunidades");
                });

            modelBuilder.Entity("Persistence.Models.Empresa", b =>
                {
                    b.Navigation("ActividadOportunidades");

                    b.Navigation("Contactos");

                    b.Navigation("Oportunidades");
                });

            modelBuilder.Entity("Persistence.Models.EstadoCliente", b =>
                {
                    b.Navigation("Contactos");

                    b.Navigation("Empresas");

                    b.Navigation("Oportunidades");
                });

            modelBuilder.Entity("Persistence.Models.EtapaComercial", b =>
                {
                    b.Navigation("HistorialEtapaIdEtapaAnteriorNavigations");

                    b.Navigation("HistorialEtapaIdNuevaEtapaNavigations");

                    b.Navigation("Oportunidades");
                });

            modelBuilder.Entity("Persistence.Models.Modalidad", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("Persistence.Models.NivelIngles", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("Persistence.Models.Oportunidad", b =>
                {
                    b.Navigation("ActividadOportunidades");

                    b.Navigation("HistorialEtapas");

                    b.Navigation("LogOportunidadCambios");

                    b.Navigation("OportunidadItems");
                });

            modelBuilder.Entity("Persistence.Models.OrigenComercial", b =>
                {
                    b.Navigation("Contactos");

                    b.Navigation("Empresas");

                    b.Navigation("Oportunidades");
                });

            modelBuilder.Entity("Persistence.Models.Permiso", b =>
                {
                    b.Navigation("PermisoRoles");
                });

            modelBuilder.Entity("Persistence.Models.Rol", b =>
                {
                    b.Navigation("PermisoRoles");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("Persistence.Models.Servicio", b =>
                {
                    b.Navigation("OportunidadItems");

                    b.Navigation("Oportunidades");
                });

            modelBuilder.Entity("Persistence.Models.Usuario", b =>
                {
                    b.Navigation("ActividadOportunidades");

                    b.Navigation("HistorialEtapas");

                    b.Navigation("LogOportunidadCambios");

                    b.Navigation("Oportunidades");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
