/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/Contacto/AltaContacto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Da de alta un nuevo contacto. */
        post: operations["AltaContacto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Contacto/DatosContacto/{idContacto}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtiene los datos de un contacto por id. */
        get: operations["DatosContacto"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Contacto/ListadoContactos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtiene el listado de todos los contactos. */
        get: operations["ListadoContactos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Contacto/ModificarContacto/{idContacto}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Modifica los datos de un contacto existente. */
        post: operations["ModificarContacto"];
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Modifica solo los campos enviados de un contacto y permite borrar valores opcionales.
         * @description Un campo omitido conserva su valor. Un null explícito borra un campo opcional, pero no puede borrar
         *     nombre, apellido ni correo. Un objeto vacío no cambia el contacto. Los campos desconocidos se rechazan.
         *     El POST de esta misma ruta conserva su comportamiento anterior: null no modifica.
         */
        patch: operations["PatchContacto"];
        trace?: never;
    };
    "/Contacto/HistorialEtapas/{idContacto}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtiene el historial de cambios de etapa de las oportunidades del contacto. */
        get: operations["HistorialEtapasContacto"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Empresa/AltaEmpresa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Da de alta una nueva empresa. */
        post: operations["AltaEmpresa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Empresa/DatosEmpresa/{idEmpresa}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtiene los datos de una empresa por id. */
        get: operations["DatosEmpresa"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Empresa/ListadoEmpresas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtiene el listado de todas las empresas. */
        get: operations["ListadoEmpresas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Empresa/ModificarEmpresa/{idEmpresa}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Modifica los datos de una empresa existente. */
        post: operations["ModificarEmpresa"];
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Modifica solo los campos enviados de una empresa y permite borrar valores opcionales.
         * @description Un campo omitido conserva su valor. Un null explícito borra un campo opcional, pero no puede borrar
         *     razonSocial. Un objeto vacío no cambia la empresa. Los campos desconocidos se rechazan.
         *     El POST de esta misma ruta conserva su comportamiento anterior: null no modifica.
         */
        patch: operations["PatchEmpresa"];
        trace?: never;
    };
    "/EstadosCliente/ListadoEstadosCliente": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtiene el listado de estados de cliente.
         * @description Incluye todos los registros, ordenados por descripción e id. Devuelve una lista vacía si no hay registros.
         */
        get: operations["ListadoEstadosCliente"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/EtapasComerciales/ListadoEtapasComerciales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtiene el listado de etapas comerciales.
         * @description Incluye todos los registros, ordenados por orden e id. Devuelve una lista vacía si no hay registros. No incluye oportunidades; también devuelve etapas sin oportunidades.
         */
        get: operations["ListadoEtapasComerciales"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Login/Register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registra un nuevo usuario, hasheando su contraseña. */
        post: operations["Register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Login/Login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autentica un usuario por username y contraseña. */
        post: operations["Login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Oportunidades/AltaOportunidad": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Da de alta una nueva oportunidad. */
        post: operations["AltaOportunidad"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Oportunidades/OportunidadesPorEtapa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Devuelve todas las oportunidades agrupadas por etapa comercial (vista de embudo). */
        get: operations["OportunidadesPorEtapa"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Oportunidades/DatosOportunidad/{idOportunidad}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtiene los datos de una oportunidad por id. */
        get: operations["DatosOportunidad"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Oportunidades/ModificarOportunidad/{idOportunidad}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Modifica los datos de una oportunidad existente (no cambia su etapa comercial). */
        post: operations["ModificarOportunidad"];
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Modifica solo los campos enviados de una oportunidad y permite borrar valores opcionales.
         * @description Un campo omitido conserva su valor. Un null explícito borra un campo opcional, pero no puede borrar
         *     titulo ni idUsuario. Un objeto vacío no cambia la oportunidad. La etapa se actualiza exclusivamente
         *     mediante su endpoint específico; fecha de cierre queda fuera del contrato actual. Los campos desconocidos
         *     se rechazan.
         */
        patch: operations["PatchOportunidad"];
        trace?: never;
    };
    "/Oportunidades/UpdateEtapaOportunidad/{idOportunidad}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mueve una oportunidad a una nueva etapa comercial y lo asienta en el historial. */
        post: operations["UpdateEtapaOportunidad"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/OrigenesComerciales/ListadoOrigenesComerciales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtiene el listado de orígenes comerciales.
         * @description Incluye todos los registros, ordenados por descripción e id. Devuelve una lista vacía si no hay registros.
         */
        get: operations["ListadoOrigenesComerciales"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Servicios/ListadoServicios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtiene los servicios activos disponibles para las oportunidades.
         * @description Ordenados por nombre e id. Excluye activo falso o nulo; devuelve una lista vacía si no hay servicios activos.
         */
        get: operations["ListadoServicios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Datos de un contacto. Los campos `*Descripcion`/`*RazonSocial` acompañan a su id correspondiente
         *     con el valor legible desde la tabla referenciada, para que el frontend no tenga que resolverlo con una
         *     consulta aparte.
         */
        ContactoResponse: {
            /** Format: int32 */
            id: number | string;
            nombre: string;
            apellido: string;
            documento: null | string;
            cargo: null | string;
            correo: string;
            telefono: null | string;
            /** Format: int32 */
            idEstado: null | number | string;
            estadoDescripcion: null | string;
            /** Format: int32 */
            idOrigen: null | number | string;
            origenDescripcion: null | string;
            /** Format: int32 */
            idEmpresa: null | number | string;
            empresaRazonSocial: null | string;
            observaciones: null | string;
        };
        /** @description Payload para dar de alta un contacto. */
        CreateContactoRequest: {
            nombre: string;
            apellido: string;
            correo: string;
            documento?: null | string;
            cargo?: null | string;
            telefono?: null | string;
            /** Format: int32 */
            idEstado?: null | number | string;
            /** Format: int32 */
            idOrigen?: null | number | string;
            /** Format: int32 */
            idEmpresa?: null | number | string;
            observaciones?: null | string;
        };
        /** @description Payload para dar de alta una empresa. */
        CreateEmpresaRequest: {
            razonSocial: string;
            cuit?: null | string;
            industria?: null | string;
            correo?: null | string;
            telefono?: null | string;
            direccion?: null | string;
            /** Format: int32 */
            idEstado?: null | number | string;
            /** Format: int32 */
            idOrigen?: null | number | string;
            observaciones?: null | string;
        };
        /** @description Payload para registrar una nueva oportunidad. */
        CreateOportunidadRequest: {
            titulo: string;
            /**
             * Format: int32
             * @description Usuario responsable de la oportunidad (toda oportunidad debe tener un responsable).
             */
            idUsuario: number | string;
            /**
             * Format: int32
             * @description Etapa comercial inicial de la oportunidad.
             */
            idEtapa: number | string;
            /**
             * Format: int32
             * @description Empresa asociada. La oportunidad debe tener empresa y/o contacto.
             */
            idEmpresa?: null | number | string;
            /**
             * Format: int32
             * @description Contacto asociado. Si se indica empresa, el contacto debe pertenecer a ella. Sin empresa puede seleccionarse cualquier contacto existente.
             */
            idContacto?: null | number | string;
            /** Format: int32 */
            idServicio?: null | number | string;
            /** Format: date */
            fechaEstimadaCierre?: null | string;
            /** Format: int32 */
            idOrigen?: null | number | string;
            /** Format: int32 */
            idEstado?: null | number | string;
            observaciones?: null | string;
        };
        /**
         * @description Datos de una empresa. Los campos `*Descripcion` acompañan a su id correspondiente con el valor
         *     legible desde la tabla referenciada (por ejemplo, string? EmpresaResponse.EstadoDescripcion es la descripción de
         *     int? EmpresaResponse.IdEstado), para que el frontend no tenga que resolverlo con una consulta aparte.
         */
        EmpresaResponse: {
            /** Format: int32 */
            id: number | string;
            razonSocial: string;
            cuit: null | string;
            industria: null | string;
            correo: null | string;
            telefono: null | string;
            direccion: null | string;
            /** Format: int32 */
            idEstado: null | number | string;
            estadoDescripcion: null | string;
            /** Format: int32 */
            idOrigen: null | number | string;
            origenDescripcion: null | string;
            observaciones: null | string;
        };
        /** @description Datos de consulta del catálogo de estados de cliente. */
        EstadoClienteResponse: {
            /** Format: int32 */
            id: number | string;
            descripcion: string;
        };
        /** @description Datos de consulta del catálogo de etapas comerciales. */
        EtapaComercialResponse: {
            /** Format: int32 */
            id: number | string;
            nombre: string;
            descripcion: null | string;
            /** Format: int32 */
            orden: number | string;
        };
        /** @description Una etapa comercial junto con las oportunidades que se encuentran en ella. */
        EtapaConOportunidadesResponse: {
            /** Format: int32 */
            idEtapa: number | string;
            nombre: string;
            /** Format: int32 */
            orden: number | string;
            oportunidades: components["schemas"]["OportunidadResumenResponse"][];
        };
        /** @description Un cambio de etapa comercial registrado en el historial de una oportunidad del contacto. */
        HistorialEtapaResponse: {
            /** Format: int32 */
            id: number | string;
            /** Format: int32 */
            idOportunidad: null | number | string;
            oportunidadTitulo: null | string;
            /** Format: int32 */
            idEtapaAnterior: null | number | string;
            etapaAnteriorNombre: null | string;
            /** Format: int32 */
            idNuevaEtapa: null | number | string;
            etapaNuevaNombre: null | string;
            /** Format: date-time */
            fecha: null | string;
            /** Format: int32 */
            idUsuario: null | number | string;
            usuarioNombre: null | string;
            usuarioApellido: null | string;
            observacion: null | string;
        };
        /** @description Payload para iniciar sesión. */
        LoginRequest: {
            username: string;
            password: string;
        };
        /**
         * @description Detalle completo de una oportunidad. Los campos `*Nombre`/`*Apellido`/`*RazonSocial`/
         *     `*Descripcion` acompañan a su id correspondiente con el valor legible desde la tabla referenciada,
         *     para que el frontend no tenga que resolverlo con una consulta aparte.
         */
        OportunidadResponse: {
            /** Format: int32 */
            id: number | string;
            titulo: string;
            /** Format: int32 */
            idUsuario: null | number | string;
            usuarioNombre: null | string;
            usuarioApellido: null | string;
            /** Format: int32 */
            idEmpresa: null | number | string;
            empresaRazonSocial: null | string;
            /** Format: int32 */
            idContacto: null | number | string;
            contactoNombre: null | string;
            contactoApellido: null | string;
            /** Format: int32 */
            idServicio: null | number | string;
            servicioNombre: null | string;
            /** Format: int32 */
            idEtapa: null | number | string;
            etapaNombre: null | string;
            /** Format: date */
            fechaEstimadaCierre: null | string;
            /** Format: date-time */
            fechaCierre: null | string;
            /** Format: int32 */
            idOrigen: null | number | string;
            origenDescripcion: null | string;
            /** Format: int32 */
            idEstado: null | number | string;
            estadoDescripcion: null | string;
            observaciones: null | string;
        };
        /** @description Resumen de una oportunidad para las vistas de embudo comercial. */
        OportunidadResumenResponse: {
            /** Format: int32 */
            id: number | string;
            titulo: string;
            /** Format: int32 */
            idEmpresa: null | number | string;
            empresaRazonSocial: null | string;
            /** Format: int32 */
            idContacto: null | number | string;
            contactoNombre: null | string;
            contactoApellido: null | string;
            /** Format: int32 */
            idUsuario: null | number | string;
            usuarioNombre: null | string;
            usuarioApellido: null | string;
            /** Format: date */
            fechaEstimadaCierre: null | string;
        };
        /** @description Datos de consulta del catálogo de orígenes comerciales. */
        OrigenComercialResponse: {
            /** Format: int32 */
            id: number | string;
            descripcion: string;
        };
        /**
         * @description Actualización parcial de contacto: un campo omitido conserva su valor y un null explícito
         *     borra un campo opcional. Nombre, apellido y correo no pueden borrarse. No admite campos desconocidos.
         */
        PatchContactoRequest: {
            /** @description Nombre; si se envía, no puede ser null, vacío ni solo espacios. */
            nombre?: null | string;
            /** @description Apellido; si se envía, no puede ser null, vacío ni solo espacios. */
            apellido?: null | string;
            /** @description Correo; si se envía, debe tener formato de email y no puede ser null, vacío ni solo espacios. */
            correo?: null | string;
            /** @description Documento; null elimina el valor guardado. */
            documento?: null | string;
            /** @description Cargo; null elimina el valor guardado. */
            cargo?: null | string;
            /** @description Teléfono; null elimina el valor guardado. */
            telefono?: null | string;
            /**
             * Format: int32
             * @description Estado de cliente existente; null elimina la asociación.
             */
            idEstado?: null | number | string;
            /**
             * Format: int32
             * @description Origen comercial existente; null elimina la asociación.
             */
            idOrigen?: null | number | string;
            /**
             * Format: int32
             * @description Empresa existente; null elimina la asociación si el contacto no tiene oportunidades asociadas.
             */
            idEmpresa?: null | number | string;
            /** @description Observaciones; null elimina el valor guardado. */
            observaciones?: null | string;
        };
        /**
         * @description Actualización parcial de empresa: un campo omitido conserva su valor y un null explícito
         *     borra un campo opcional. RazonSocial no puede borrarse. No admite campos desconocidos.
         */
        PatchEmpresaRequest: {
            /** @description Razón social. Si se envía, no puede ser null, vacía ni contener solo espacios. */
            razonSocial?: null | string;
            /** @description CUIT; null elimina el valor guardado. */
            cuit?: null | string;
            /** @description Industria; null elimina el valor guardado. */
            industria?: null | string;
            /** @description Correo electrónico; null elimina el valor guardado. */
            correo?: null | string;
            /** @description Teléfono; null elimina el valor guardado. */
            telefono?: null | string;
            /** @description Dirección; null elimina el valor guardado. */
            direccion?: null | string;
            /**
             * Format: int32
             * @description Estado de cliente existente; null elimina la asociación.
             */
            idEstado?: null | number | string;
            /**
             * Format: int32
             * @description Origen comercial existente; null elimina la asociación.
             */
            idOrigen?: null | number | string;
            /** @description Observaciones; null elimina el valor guardado. */
            observaciones?: null | string;
        };
        /**
         * @description Actualización parcial de oportunidad. Un campo omitido conserva su valor y un null explícito borra un
         *     campo opcional. Titulo e IdUsuario no pueden borrarse. La etapa se modifica solo mediante su endpoint
         *     específico; FechaCierre queda fuera del contrato de actualización actual. No admite campos desconocidos.
         */
        PatchOportunidadRequest: {
            /** @description Título; si se envía, no puede ser null, vacío ni solo espacios. */
            titulo?: null | string;
            /**
             * Format: int32
             * @description Usuario responsable existente; si se envía no puede ser null.
             */
            idUsuario?: null | number | string;
            /**
             * Format: int32
             * @description Empresa existente; null elimina la asociación si permanece un contacto.
             */
            idEmpresa?: null | number | string;
            /**
             * Format: int32
             * @description Contacto existente; null elimina la asociación si permanece una empresa.
             */
            idContacto?: null | number | string;
            /**
             * Format: int32
             * @description Servicio existente; null elimina la asociación.
             */
            idServicio?: null | number | string;
            /**
             * Format: date
             * @description Fecha estimada de cierre; null elimina el valor guardado.
             */
            fechaEstimadaCierre?: null | string;
            /**
             * Format: int32
             * @description Origen comercial existente; null elimina la asociación.
             */
            idOrigen?: null | number | string;
            /**
             * Format: int32
             * @description Estado de cliente existente; null elimina la asociación.
             */
            idEstado?: null | number | string;
            /** @description Observaciones; null elimina el valor guardado. */
            observaciones?: null | string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        /** @description Payload para registrar un nuevo usuario. */
        RegisterRequest: {
            nombre: string;
            apellido: string;
            correo: string;
            username: string;
            password: string;
        };
        /** @description Servicio activo disponible para seleccionar al crear o modificar una oportunidad. */
        ServicioResponse: {
            /** Format: int32 */
            id: number | string;
            nombre: string;
            descripcion: null | string;
            /** Format: double */
            precioReferencia: number | string;
        };
        /**
         * @description Payload para modificar un contacto existente. Solo los campos enviados (no nulos) se actualizan; el resto
         *     conserva su valor actual.
         */
        UpdateContactoRequest: {
            nombre?: null | string;
            apellido?: null | string;
            correo?: null | string;
            documento?: null | string;
            cargo?: null | string;
            telefono?: null | string;
            /** Format: int32 */
            idEstado?: null | number | string;
            /** Format: int32 */
            idOrigen?: null | number | string;
            /** Format: int32 */
            idEmpresa?: null | number | string;
            observaciones?: null | string;
        };
        /**
         * @description Payload para modificar una empresa existente. Solo los campos enviados (no nulos) se actualizan; el resto
         *     conserva su valor actual.
         */
        UpdateEmpresaRequest: {
            razonSocial?: null | string;
            cuit?: null | string;
            industria?: null | string;
            correo?: null | string;
            telefono?: null | string;
            direccion?: null | string;
            /** Format: int32 */
            idEstado?: null | number | string;
            /** Format: int32 */
            idOrigen?: null | number | string;
            observaciones?: null | string;
        };
        /** @description Payload para mover una oportunidad a una nueva etapa comercial. */
        UpdateEtapaOportunidadRequest: {
            /**
             * Format: int32
             * @description Id de la nueva etapa comercial.
             */
            idNuevaEtapa: number | string;
            /**
             * Format: int32
             * @description Usuario que realiza el cambio, para dejarlo asentado en el historial.
             */
            idUsuario?: null | number | string;
            /** @description Observación opcional sobre el cambio de etapa. */
            observacion?: null | string;
        };
        /**
         * @description Payload para modificar una oportunidad existente. Solo los campos enviados (no nulos) se actualizan; el
         *     resto conserva su valor actual. No incluye la etapa comercial: eso es responsabilidad exclusiva de
         *     UpdateEtapaOportunidadRequest.
         *     La combinación final de empresa y contacto debe ser compatible: si ambos están presentes,
         *     el contacto debe pertenecer a esa empresa, incluyendo los valores conservados al omitir campos.
         */
        UpdateOportunidadRequest: {
            titulo?: null | string;
            /** Format: int32 */
            idUsuario?: null | number | string;
            /** Format: int32 */
            idEmpresa?: null | number | string;
            /** Format: int32 */
            idContacto?: null | number | string;
            /** Format: int32 */
            idServicio?: null | number | string;
            /** Format: date */
            fechaEstimadaCierre?: null | string;
            /** Format: int32 */
            idOrigen?: null | number | string;
            /** Format: int32 */
            idEstado?: null | number | string;
            observaciones?: null | string;
        };
        /** @description Datos de un usuario (nunca incluye el hash de la contraseña). */
        UsuarioResponse: {
            /** Format: int32 */
            id: number | string;
            nombre: string;
            apellido: string;
            correo: string;
            username: string;
            activo: null | boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AltaContacto: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateContactoRequest"];
                "text/json": components["schemas"]["CreateContactoRequest"];
                "application/*+json": components["schemas"]["CreateContactoRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ContactoResponse"];
                    "application/json": components["schemas"]["ContactoResponse"];
                    "text/json": components["schemas"]["ContactoResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                    "text/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    DatosContacto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idContacto: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ContactoResponse"];
                    "application/json": components["schemas"]["ContactoResponse"];
                    "text/json": components["schemas"]["ContactoResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                    "text/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListadoContactos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ContactoResponse"][];
                    "application/json": components["schemas"]["ContactoResponse"][];
                    "text/json": components["schemas"]["ContactoResponse"][];
                };
            };
        };
    };
    ModificarContacto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idContacto: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateContactoRequest"];
                "text/json": components["schemas"]["UpdateContactoRequest"];
                "application/*+json": components["schemas"]["UpdateContactoRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ContactoResponse"];
                    "application/json": components["schemas"]["ContactoResponse"];
                    "text/json": components["schemas"]["ContactoResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                    "text/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                    "text/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    PatchContacto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idContacto: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchContactoRequest"];
                "text/json": components["schemas"]["PatchContactoRequest"];
                "application/*+json": components["schemas"]["PatchContactoRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ContactoResponse"];
                    "application/json": components["schemas"]["ContactoResponse"];
                    "text/json": components["schemas"]["ContactoResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                    "text/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                    "text/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    HistorialEtapasContacto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idContacto: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["HistorialEtapaResponse"][];
                    "application/json": components["schemas"]["HistorialEtapaResponse"][];
                    "text/json": components["schemas"]["HistorialEtapaResponse"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                    "text/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    AltaEmpresa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEmpresaRequest"];
                "text/json": components["schemas"]["CreateEmpresaRequest"];
                "application/*+json": components["schemas"]["CreateEmpresaRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["EmpresaResponse"];
                    "application/json": components["schemas"]["EmpresaResponse"];
                    "text/json": components["schemas"]["EmpresaResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                    "text/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    DatosEmpresa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idEmpresa: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["EmpresaResponse"];
                    "application/json": components["schemas"]["EmpresaResponse"];
                    "text/json": components["schemas"]["EmpresaResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                    "text/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListadoEmpresas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["EmpresaResponse"][];
                    "application/json": components["schemas"]["EmpresaResponse"][];
                    "text/json": components["schemas"]["EmpresaResponse"][];
                };
            };
        };
    };
    ModificarEmpresa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idEmpresa: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEmpresaRequest"];
                "text/json": components["schemas"]["UpdateEmpresaRequest"];
                "application/*+json": components["schemas"]["UpdateEmpresaRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["EmpresaResponse"];
                    "application/json": components["schemas"]["EmpresaResponse"];
                    "text/json": components["schemas"]["EmpresaResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                    "text/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                    "text/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    PatchEmpresa: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idEmpresa: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchEmpresaRequest"];
                "text/json": components["schemas"]["PatchEmpresaRequest"];
                "application/*+json": components["schemas"]["PatchEmpresaRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["EmpresaResponse"];
                    "application/json": components["schemas"]["EmpresaResponse"];
                    "text/json": components["schemas"]["EmpresaResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                    "text/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                    "text/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListadoEstadosCliente: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["EstadoClienteResponse"][];
                    "application/json": components["schemas"]["EstadoClienteResponse"][];
                    "text/json": components["schemas"]["EstadoClienteResponse"][];
                };
            };
        };
    };
    ListadoEtapasComerciales: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["EtapaComercialResponse"][];
                    "application/json": components["schemas"]["EtapaComercialResponse"][];
                    "text/json": components["schemas"]["EtapaComercialResponse"][];
                };
            };
        };
    };
    Register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
                "text/json": components["schemas"]["RegisterRequest"];
                "application/*+json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["UsuarioResponse"];
                    "application/json": components["schemas"]["UsuarioResponse"];
                    "text/json": components["schemas"]["UsuarioResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                    "text/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    Login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
                "text/json": components["schemas"]["LoginRequest"];
                "application/*+json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["UsuarioResponse"];
                    "application/json": components["schemas"]["UsuarioResponse"];
                    "text/json": components["schemas"]["UsuarioResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                    "text/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    AltaOportunidad: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOportunidadRequest"];
                "text/json": components["schemas"]["CreateOportunidadRequest"];
                "application/*+json": components["schemas"]["CreateOportunidadRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["OportunidadResponse"];
                    "application/json": components["schemas"]["OportunidadResponse"];
                    "text/json": components["schemas"]["OportunidadResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                    "text/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    OportunidadesPorEtapa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["EtapaConOportunidadesResponse"][];
                    "application/json": components["schemas"]["EtapaConOportunidadesResponse"][];
                    "text/json": components["schemas"]["EtapaConOportunidadesResponse"][];
                };
            };
        };
    };
    DatosOportunidad: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idOportunidad: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["OportunidadResponse"];
                    "application/json": components["schemas"]["OportunidadResponse"];
                    "text/json": components["schemas"]["OportunidadResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                    "text/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ModificarOportunidad: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idOportunidad: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOportunidadRequest"];
                "text/json": components["schemas"]["UpdateOportunidadRequest"];
                "application/*+json": components["schemas"]["UpdateOportunidadRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["OportunidadResponse"];
                    "application/json": components["schemas"]["OportunidadResponse"];
                    "text/json": components["schemas"]["OportunidadResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                    "text/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                    "text/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    PatchOportunidad: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idOportunidad: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchOportunidadRequest"];
                "text/json": components["schemas"]["PatchOportunidadRequest"];
                "application/*+json": components["schemas"]["PatchOportunidadRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["OportunidadResponse"];
                    "application/json": components["schemas"]["OportunidadResponse"];
                    "text/json": components["schemas"]["OportunidadResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                    "text/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                    "text/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    UpdateEtapaOportunidad: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                idOportunidad: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEtapaOportunidadRequest"];
                "text/json": components["schemas"]["UpdateEtapaOportunidadRequest"];
                "application/*+json": components["schemas"]["UpdateEtapaOportunidadRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["OportunidadResponse"];
                    "application/json": components["schemas"]["OportunidadResponse"];
                    "text/json": components["schemas"]["OportunidadResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                    "text/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ProblemDetails"];
                    "application/json": components["schemas"]["ProblemDetails"];
                    "text/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ListadoOrigenesComerciales: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["OrigenComercialResponse"][];
                    "application/json": components["schemas"]["OrigenComercialResponse"][];
                    "text/json": components["schemas"]["OrigenComercialResponse"][];
                };
            };
        };
    };
    ListadoServicios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": components["schemas"]["ServicioResponse"][];
                    "application/json": components["schemas"]["ServicioResponse"][];
                    "text/json": components["schemas"]["ServicioResponse"][];
                };
            };
        };
    };
}
